"""Generate unified/REPORT.md: which hands are mapped into the canonical space and which are not (and why)."""
from __future__ import annotations

import pandas as pd
import yaml

from .hands import REPO, registry

UNI = REPO / "unified"


def _md(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows():
        lines.append("| " + " | ".join("" if pd.isna(v) else str(v) for v in r.values) + " |")
    return "\n".join(lines)


def build() -> str:
    ds_cfg = yaml.safe_load(open(REPO / "config/datasets.yaml"))["datasets"]
    reg = registry()
    models = reg["hand_models"]
    val = reg.get("validation", {})
    hs = pd.read_parquet(UNI / "hand_streams.parquet")
    man = pd.read_parquet(UNI / "manifest.parquet")
    cams = pd.read_parquet(UNI / "cameras.parquet")

    # ---------------- hand coverage from the strict verification gate (config/verification.yaml)
    ver = yaml.safe_load(open(REPO / "config/verification.yaml"))
    rows = []
    for mid, v in ver["mappings"].items():
        sub = hs[hs.mapping_id == mid]
        ex = sub[sub.canonicalization_status.isin(["ok", "excluded_not_verified"])]
        fails = [k for k, c in v.get("checks", {}).items() if c != "pass"]
        rows.append(dict(dataset=sub.dataset_id.iloc[0] if len(sub) else mid.split("__")[0],
                         hand=f"{sub.hand_family.iloc[0]}/{sub.side.iloc[0]}" if len(sub) else mid.split("__")[1],
                         hand_model_id=sub.hand_model_id.iloc[0] if len(sub) else "",
                         model_status=sub.hand_model_status.iloc[0] if len(sub) else "",
                         state_source=",".join(sorted(set(sub.state_source))),
                         verification=v["status"], failed_checks=",".join(fails),
                         episodes=len(ex), samples=int(ex.n_samples.sum()),
                         reason=" ".join(str(v.get("reason") or v.get("note") or "").split())))
    cov = pd.DataFrame(rows)
    notproc = pd.DataFrame([dict(hand=k, decision=" ".join(v.split()),
                                 native_streams_in_dataset=int((hs.dataset_id == k.split("/")[0]).sum()))
                            for k, v in ver.get("not_processed", {}).items()])
    for fam, m in reg.get("missing_models", {}).items():
        if m.get("status") == "no_data" or "revo2" in fam:
            notproc.loc[len(notproc)] = dict(hand=f"{m['datasets'][0]}/{fam}", decision=m["reason"], native_streams_in_dataset=0)
    notproc.loc[len(notproc)] = dict(hand="robotacdex/brainco_revo2", decision="model ready, dataset not public",
                                     native_streams_in_dataset=0)

    # ---------------- per dataset sample summary
    summ = []
    for ds, g in man.groupby("dataset_id"):
        c = cams[cams.dataset_id == ds]
        summ.append(dict(dataset=ds, episodes=len(g), hours=round(g.duration_s.sum() / 3600, 3),
                         text=f"{g.has_text.mean():.0%}", annotation_source=",".join(sorted(set(g.annotation_source))),
                         cameras_per_ep=round(g.n_cameras.mean(), 1), cameras_local=round(g.n_cameras_local.mean(), 1),
                         depth=bool(g.has_depth.any()), tactile=bool(g.has_tactile.any()),
                         contact_labels=bool(g.has_contact_labels.any()),
                         hand_streams=int((hs.dataset_id == ds).sum()),
                         canonical_ok=int(((hs.dataset_id == ds) & (hs.canonicalization_status == "ok")).sum())))
    summ = pd.DataFrame(summ)

    status_counts = hs.groupby(["dataset_id", "side", "canonicalization_status"]).size().reset_index(name="streams")
    mapped = cov[cov.verification == "verified"]
    notmapped = cov[cov.verification != "verified"]
    nn = (UNI / "validation/embodiment_gap.txt")
    out = [
        "# UnifiedDex — conversion report (sample corpus)",
        "",
        "Generated by `python -m unidex.report`. Canonical representation: 5 fingertips in the hand's own palm frame "
        "(`fingertips_palm_m`, `fingertips_palm_norm`), order thumb, index, middle, ring, pinky.",
        "",
        "Strict policy (config/verification.yaml): geometry is stored ONLY for fully verified (dataset, hand) pairs "
        "(V1 exact model, V2 official mapping, V3 measured state, V4 visual check, V5 joint limits, V6 timestamps). "
        "Everything else keeps native data only.",
        "",
        "## 1. VERIFIED — canonical geometry stored",
        "",
        _md(mapped.drop(columns=["verification", "failed_checks"])),
        "",
        "## 2. EXCLUDED — model and mapping exist, but not 100% verified (native data only)",
        "",
        _md(notmapped),
        "",
        "## 2b. NOT PROCESSED — no model / no usable mapping / no data (native data only)",
        "",
        _md(notproc),
        "",
        "## 3. Sample corpus per dataset",
        "",
        _md(summ),
        "",
        "## 4. Canonicalization status per hand stream",
        "",
        _md(status_counts),
        "",
        "## 5. Cross-embodiment check",
        "",
        "![pca](validation/cross_embodiment_pca.png)",
        "",
        "```",
        nn.read_text() if nn.exists() else "(run cross-embodiment check)",
        "```",
        "",
        "Decision on the thumb gap and clustering features: GRASP_LABELING.md.",
        "",
        "Per-hand visual checks: `unified/validation/*.png` (RGB frame + canonical skeleton at the same timestamp).",
    ]
    return "\n".join(out)


if __name__ == "__main__":
    (UNI / "REPORT.md").write_text(build())
    print((UNI / "REPORT.md").read_text()[:6000])
