"""Extract the XHand1 sub-trees (right / left) from RobotEra's official STAR1 URDF (roboterax/models, BSD-3).

Decision 2026-09-29 (user): the STAR1 hand is accepted as the official XHand1 model. Its finger joints are identical
to the third-party SPIDER XHand URDF (origins/axes equal; right_hand_mid_joint2 upper limit 1.92 vs 1.94).
Output: external_hand_models/roboterax_models/xhand1_{right,left}_star1.urdf (root = <side>_hand_link, meshes
referenced relative to the STAR1 urdf directory). Deterministic: re-run after updating the clone.
"""
import xml.etree.ElementTree as ET
from pathlib import Path

SRC = Path("external_hand_models/roboterax_models/models/star1/urdf/l3_with_hand_fixedpin_xml.urdf")
OUT = Path("external_hand_models/roboterax_models")

tree = ET.parse(SRC)
root = tree.getroot()
joints = root.findall("joint")
for side in ("right", "left"):
    keep = {f"{side}_hand_link"}
    grew = True
    while grew:  # links below <side>_hand_link
        grew = False
        for j in joints:
            p, c = j.find("parent").get("link"), j.find("child").get("link")
            if p in keep and c not in keep:
                keep.add(c); grew = True
    robot = ET.Element("robot", name=f"xhand1_{side}_from_star1")
    robot.append(ET.Comment(f" generated by scripts/models/extract_star1_xhand.py from {SRC} (RobotEra STAR1, BSD-3) "))
    for l in root.findall("link"):
        if l.get("name") in keep:
            for m in l.iter("mesh"):
                m.set("filename", str((SRC.parent / m.get("filename")).resolve().relative_to(OUT.resolve())))
            robot.append(l)
    for j in joints:
        if j.find("parent").get("link") in keep and j.find("child").get("link") in keep:
            robot.append(j)
    ET.indent(robot)
    out = OUT / f"xhand1_{side}_star1.urdf"
    ET.ElementTree(robot).write(out, xml_declaration=True, encoding="utf-8")
    print(out, len(keep), "links")
